#!/bin/bash

wget --no-check-certificate -O data/data.tar.gz  https://github.com/v-yurchenko/nanogpt/blob/main/data/data.tar.gz?raw=true
wget --no-check-certificate -O data/news_meta.pkl  https://github.com/v-yurchenko/nanogpt/blob/main/data/news_meta.pkl?raw=true
wget --no-check-certificate -O data/news_train.pt  https://github.com/v-yurchenko/nanogpt/blob/main/data/news_train.pt?raw=true
wget --no-check-certificate -O data/news_val.pt  https://github.com/v-yurchenko/nanogpt/blob/main/data/news_val.pt?raw=true
wget --no-check-certificate -O model/news_finetuned.pt  https://github.com/v-yurchenko/nanogpt/blob/main/model/news_finetuned.pt?raw=true
wget --no-check-certificate -O model/news.pt  https://github.com/v-yurchenko/nanogpt/blob/main/model/news.pt?raw=true

